version: '2.2'

services:
  transcribe:
    build:
      context: ./app/VoiceToText
      dockerfile: Dockerfile
    command:
      - python
      - /app/transcribeMain.py

#  llm:
#    build:
#      context: ./app/Llm
#      dockerfile: Dockerfile
#    command:
#      - python
##      Endpoint
#      - /app/main.py
#
#  TextToVoice:
#    build:
#      context: ./app/TextToVoice
#      dockerfile: Dockerfile
#    command:
#      - python
#      #      Endpoint
#      - /app/main.py
#      -
#  VoiceToVideo:
#    build:
#      context: ./app/VoiceToVideo
#      dockerfile: Dockerfile
#    command:
#      - python
#      #      Endpoint
#      - /app/main.py
