version: '2.2'

services:
  transcribe:
    build:
      context: ./app/VoiceToText
      dockerfile: Dockerfile
    volumes:
      - ./app/TextToVoice/app:/text-to-voice-app
    ports:
      - "5000:5000"

  llm:
    depends_on:
      - transcribe
    build:
      context: ./app/Llm
      dockerfile: Dockerfile
    command:
      - python
      - /llm-app/start_llm.py
    volumes:
      - ./app/Llm/app:/llm-app

  texttovoice:
    depends_on:
      - llm
    build:
      context: ./app/TextToVoice
      dockerfile: Dockerfile
    command:
      - python
      - /text-to-voice-app/start_texttovoice.py
    volumes:
      - ./app/TextToVoice/app:/text-to-voice-app
