version: '2.2'

services:
  transcribe:
    build:
      context: .
      dockerfile: docker/Dockerfile_VoiceToText
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    command: ["python", "/app/app/VoiceToText/transcribeMain.py"]



# This will be updated to run the LLM
#  llm:
#    depends_on:
#      - transcribe
#    build:
#        context: .
#        dockerfile: docker/Dockerfile_Llm
#    volumes:
#      - .:/app
#    # No command yet, we'll add that in a minute
#

# This will be updated to run the text to voice
#  textToVoice:
#    depends_on:
#      - llm
#    build:
#        context: .
#        dockerfile: docker/Dockerfile_TextToVoice
#    volumes:
#      - .:/app
#    # No command yet, we'll add that in a minute
#
