#version: '3.8' # docker-compose version enable to print diagram
services:
  # Transcribe service
  record:
    build: .
    ports:
      - "4999:4999"
    labels:
      "docker-compose_diagram.description": "Record voice"
      "docker-compose_diagram.icon": "fas fa-microphone"

  transcribe:
    depends_on:
      - record
    build:
      context: ./app/VoiceToText
      dockerfile: Dockerfile
    volumes:
      - ./app/TextToVoice/app:/text-to-voice-app
      - ./app/Llm/app:/llm-app
      - ./app/VoiceToText/app/audio_asset:/app/audio_asset
    ports:
      - "5000:5000"
    labels:
      "docker-compose_diagram.description": "Transcribe in put voice to text"
      "docker-compose_diagram.icon": "fas fa-microphone"

    # LLM service
  llm:
    depends_on:
      - transcribe
    build:
      context: ./app/Llm
      dockerfile: Dockerfile
    volumes:
      - ./app/Llm/app:/llm-app
      - ./app/TextToVoice/app:/text-to-voice-app
    ports:
      - "5002:5002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    labels:
      "docker-compose_diagram.description": "Processes transcribed Text"
      "docker-compose_diagram.icon": "fas fa-processing"


  # Text-to-voice service
  texttovoice:
    depends_on:
      - transcribe
      - llm
    build:
      context: ./app/TextToVoice
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - /text-to-voice-app/runapps.sh
    volumes:
      - ./app/Llm/app:/llm-app
      - ./app/TextToVoice/app:/text-to-voice-app
    ports:
        - "5003:5003"
        #- "5004:5004"
    labels:
      "docker-compose_diagram.description": "Converts text to voice"
      "docker-compose_diagram.icon": "fas fa-volume-up"

  voicetovideo:
    build:
      context: ./app/VoiceToVideo
      dockerfile: Dockerfile
    volumes:
      - ./app/VoiceToVideo/app:/SadTalker/results
    ports:
      - "5005:5005"
    depends_on:
      - transcribe
      - llm
      - texttovoice
    labels:
      "docker-compose_diagram.description": "Converts voice to video"
      "docker-compose_diagram.icon": "fas fa-video"
