# Use the Python 3.10 image
FROM python:3.10

# Install the latest version of poetry
RUN pip install --upgrade pip && \
    pip install poetry

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and poetry.lock files
COPY pyproject.toml poetry.lock ./

# Copy project directory
COPY app ./app

# Create an empty README.md file
#RUN touch README.md

# Configure poetry to not create a virtual environment and install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev
