# Use the Python 3.10 image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

# Install the latest version of poetry
RUN pip install --upgrade pip && \
    pip install poetry

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and poetry.lock files
COPY pyproject.toml poetry.lock ./

# Copy project directory
COPY app/VoiceToText /app

# Copy audio file into the container
COPY app/VoiceToText/audio_asset/audio.wav /app/VoiceToText/audio_asset/audio.wav

# Configure poetry to not create a virtual environment and install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev